SAR_Controller:
  ros__parameters:
    DATA_TYPE: "SIM"

    SAR_SETTINGS:
      SAR_Type: "Crazyflie"
      SAR_Config: "A30_L25"
      # Policy_Type: "PARAM_OPTIM"
      # Policy_Type: "DEEP_RL_SB3" 
      Policy_Type: "DEEP_RL_ONBOARD" 

    PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
      Plane_Type: "Landing_Surface"
      Plane_Config: "Checkerboard_L02"
      
      Pos_X_init: 3.0    # [m]
      Pos_Y_init: 0.0    # [m]
      Pos_Z_init: 2.5    # [m]
      Plane_Angle_init: 0.0 # [deg]

    CAM_SETTINGS:
      Cam_Config: "None"
      Cam_Active: False

    SAR_DC_SETTINGS:
      Console_Output: True
      Logging_Rate: 10 # [Hz]

    GROUND_SETTINGS:
      Ground_Type: "Ground_Surface"
      Ground_Config: "Desert_Pattern"

    SIM_SETTINGS:
      GUI_Flag: True
      Pause_Flag: False
      Sim_Speed: 0.5
      Sim_Slowdown_Speed: 0.5
      Landing_Slowdown_Flag: True
      Vicon_Delay: 15 # [ms]
